# Generated by Django 6.0 on 2026-01-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batsman_name', models.CharField(max_length=100)),
                ('runs_scored', models.IntegerField()),
                ('balls_faced', models.IntegerField()),
                ('in_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_runs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_team', models.CharField(max_length=100)),
                ('second_team', models.CharField(max_length=100)),
                ('match_time', models.DateTimeField()),
                ('first_team_image', models.ImageField(upload_to='team_images/')),
                ('second_team_image', models.ImageField(upload_to='team_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.IntegerField()),
            ],
        ),
    ]
