# Generated by Django 5.1.1 on 2026-01-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
